# Generated by Django 4.1.7 on 2023-03-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
