# Generated by Django 4.1.7 on 2023-03-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_inputimages_tests_outputimages_inputimages_test_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputImages',
            new_name='InputImage',
        ),
        migrations.RenameModel(
            old_name='OutputImages',
            new_name='OutputImage',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
