# Generated by Django 4.1.7 on 2023-03-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputimage',
            name='image_input_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.inputimage'),
        ),
    ]
