# Generated by Django 4.1.7 on 2023-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_image_remove_outputimage_image_input_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
